import 'package:flutter_highlight/flutter_highlight.dart';
import 'package:flutter_highlight/themes/github.dart';
import 'package:widgetgallery/view/tutorial_screens/image_widget_tutorial.dart';
import 'package:widgetgallery/view/tutorial_screens/input_tutorial/input_tutorials.dart';
import 'package:widgetgallery/view/tutorial_screens/layout_tutorial/layout_tutorial.dart';
import 'package:widgetgallery/view/tutorial_screens/list_tutorial/list_tutorial.dart';
import 'package:widgetgallery/view/tutorial_screens/scroll_tutorial/scroll_tutorial.dart';
import 'package:widgetgallery/view/tutorial_screens/text/text_tutorials.dart';
import '../../common_libraries.dart';
import 'buttons/button_tutorial.dart';

class WidgetMapping {
  static final Map<String, MapEntry<Widget, List<Widget>>> widgetMapping = {
    'Button': MapEntry(const ButtonTutorials(), [
      codeWidget(codeElevatedButtonTutorial, 'Elevated Button'),
      codeWidget(codeIconButtonTutorial, 'Icon Button'),
      codeWidget(codeOutlinedButtonTutorial, 'Outlined Button'),
      codeWidget(codeRawMaterialButtonTutorial, 'Raw Material Button'),
      codeWidget(codeFloatingActionButton, 'Floating Action Button')
    ]),

    'IconButton': MapEntry(const ButtonTutorials(), [
      codeWidget(codeElevatedButtonTutorial, 'Elevated Button'),
      codeWidget(codeIconButtonTutorial, 'Icon Button'),
      codeWidget(codeOutlinedButtonTutorial, 'Outlined Button'),
      codeWidget(codeRawMaterialButtonTutorial, 'Raw Material Button'),
      codeWidget(codeFloatingActionButton, 'Floating Action Button')
    ]),
    'OutlinedButton': MapEntry(const ButtonTutorials(), [
      codeWidget(codeElevatedButtonTutorial, 'Elevated Button'),
      codeWidget(codeIconButtonTutorial, 'Icon Button'),
      codeWidget(codeOutlinedButtonTutorial, 'Outlined Button'),
      codeWidget(codeRawMaterialButtonTutorial, 'Raw Material Button'),
      codeWidget(codeFloatingActionButton, 'Floating Action Button')
    ]),
    'RawMaterialButton': MapEntry(const ButtonTutorials(), [
      codeWidget(codeElevatedButtonTutorial, 'Elevated Button'),
      codeWidget(codeIconButtonTutorial, 'Icon Button'),
      codeWidget(codeOutlinedButtonTutorial, 'Outlined Button'),
      codeWidget(codeRawMaterialButtonTutorial, 'Raw Material Button'),
      codeWidget(codeFloatingActionButton, 'Floating Action Button')
    ]),
    'FloatingActionButton': MapEntry(const ButtonTutorials(), [
      codeWidget(codeElevatedButtonTutorial, 'Elevated Button'),
      codeWidget(codeIconButtonTutorial, 'Icon Button'),
      codeWidget(codeOutlinedButtonTutorial, 'Outlined Button'),
      codeWidget(codeRawMaterialButtonTutorial, 'Raw Material Button'),
      codeWidget(codeFloatingActionButton, 'Floating Action Button')
    ]),

    ///Text
    'Text': MapEntry(const TextTutorials(), [
      codeWidget(codeTextWidget, 'Text'),
      codeWidget(codeSelectableTextWidget, 'Selectable Text')
    ]),
    'SelectableText': MapEntry(const TextTutorials(), [
      codeWidget(codeTextWidget, 'Text'),
      codeWidget(codeSelectableTextWidget, 'Selectable Text')
    ]),

    ///List
    'ListView': MapEntry(const ListTutorial(), [
      codeWidget(codeListViewWidget, 'ListView'),
      codeWidget(codeReorderableListViewWidget, 'Reorderable ListView')
    ]),
    'ReorderableListView': MapEntry(const ListTutorial(), [
      codeWidget(codeListViewWidget, 'ListView'),
      codeWidget(codeReorderableListViewWidget, 'Reorderable ListView')
    ]),

    'Container': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Row': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Column': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'FittedBox': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),

    'Baseline': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'FractionallySizedBox': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'IntrinsicWidth': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'IntrinsicHeight': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Offstage': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'OverflowBox': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Padding': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'SizedOverflowBox': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Transform': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'ConstrainedBox': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'CustomSingleChildLayout': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'CustomMultiChildLayout': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Builder': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'ClipOval': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'ClipPath': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'PageView': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'IndexedStack': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Stack': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Wrap': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Flow': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'CustomPaint': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'BackdropFilter': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Opacity': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'ShaderMask': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Align': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Center': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'AspectRatio': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'LayoutBuilder': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'SizedBox': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Spacer': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'Divider': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),
    'SliverAppBar': MapEntry(const LayoutTutorial(), [
      codeWidget(codeContainerWidget, 'Container'),
      codeWidget(codeRowWidget, 'Row'),
      codeWidget(codeColumnWidget, 'Column'),
      codeWidget(codeFittedBoxWidget, 'FittedBox'),
      codeWidget(codeBaselineWidget, 'Baseline'),
      codeWidget(codeFractionallySizedBoxWidget, 'FractionallySizedBox'),
      codeWidget(codeIntrinsicWidthWidget, 'IntrinsicWidth'),
      codeWidget(codeIntrinsicHeightWidget, 'IntrinsicHeight'),
      codeWidget(codeOffstageWidget, 'Offstage'),
      codeWidget(codeOverflowBoxWidget, 'OverflowBox'),
      codeWidget(codePaddingWidget, 'Padding'),
      codeWidget(codeSizedOverflowBoxWidget, 'SizedOverflowBox'),
      codeWidget(codeTransformWidget, 'Transform'),
      codeWidget(codeConstrainedBoxWidget, 'ConstrainedBox'),
      codeWidget(codeCustomSingleChildLayoutWidget, 'CustomSingleChildLayout'),
      codeWidget(codeCustomMultiChildLayoutWidget, 'CustomMultiChildLayout'),
      codeWidget(codeBuilderWidget, 'Builder'),
      codeWidget(codeClipOvalWidget, 'ClipOval'),
      codeWidget(codeClipPathWidget, 'ClipPath'),
      codeWidget(codePageViewWidget, 'PageView'),
      codeWidget(codeIndexedStackWidget, 'IndexedStack'),
      codeWidget(codeStackWidget, 'Stack'),
      codeWidget(codeWrapWidget, 'Wrap'),
      codeWidget(codeFlowWidget, 'Flow'),
      codeWidget(codeCustomPaintWidget, 'CustomPaint'),
      codeWidget(codeBackdropFilterWidget, 'BackdropFilter'),
      codeWidget(codeOpacityWidget, 'Opacity'),
      codeWidget(codeShaderMaskWidget, 'ShaderMask'),
      codeWidget(codeAlignWidget, 'Align'),
      codeWidget(codeCenterWidget, 'Center'),
      codeWidget(codeAspectRatioWidget, 'AspectRatio'),
      codeWidget(codeLayoutBuilderWidget, 'LayoutBuilder'),
      codeWidget(codeSizedBoxWidget2, 'SizedBox'),
      codeWidget(codeSpacerWidget, 'Spacer'),
      codeWidget(codeDividerWidget, 'Divider'),
      codeWidget(codeSliverAppBarWidget, 'SliverAppBar'),
    ]),

    /// Layout ended
    /// Scroll started
    'SingleChildScrollView': MapEntry(
      const ScrollTutorial(),
      [
        codeWidget(codeSingleChildScrollViewWidget, 'SingleChildScrollView'),
        codeWidget(codeNestedScrollViewWidget, 'NestedScrollView'),
        codeWidget(codeCustomScrollViewWidget, 'CustomScrollView'),
        codeWidget(codeScrollConfigurationWidget, 'ScrollConfiguration'),
      ],
    ),
    'NestedScrollView': MapEntry(
      const ScrollTutorial(),
      [
        codeWidget(codeSingleChildScrollViewWidget, 'SingleChildScrollView'),
        codeWidget(codeNestedScrollViewWidget, 'NestedScrollView'),
        codeWidget(codeCustomScrollViewWidget, 'CustomScrollView'),
        codeWidget(codeScrollConfigurationWidget, 'ScrollConfiguration'),
      ],
    ),
    'CustomScrollView': MapEntry(
      const ScrollTutorial(),
      [
        codeWidget(codeSingleChildScrollViewWidget, 'SingleChildScrollView'),
        codeWidget(codeNestedScrollViewWidget, 'NestedScrollView'),
        codeWidget(codeCustomScrollViewWidget, 'CustomScrollView'),
        codeWidget(codeScrollConfigurationWidget, 'ScrollConfiguration'),
      ],
    ),
    'ScrollConfiguration': MapEntry(
      const ScrollTutorial(),
      [
        codeWidget(codeSingleChildScrollViewWidget, 'SingleChildScrollView'),
        codeWidget(codeNestedScrollViewWidget, 'NestedScrollView'),
        codeWidget(codeCustomScrollViewWidget, 'CustomScrollView'),
        codeWidget(codeScrollConfigurationWidget, 'ScrollConfiguration'),
      ],
    ),

    'TextField': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'Form': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'Slider': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'Switch': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'ToggleButtons': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'Checkbox': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),

    'DropdownButton': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'Radio': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'DatePicker': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),
    'TimePicker': MapEntry(const InputTutorial(), [
      codeWidget(codeTextFieldWidget, 'TextField'),
      codeWidget(codeFormWidget, 'Form'),
      codeWidget(codeSliderWidget, 'Slider'),
      codeWidget(codeSwitchWidget, 'Switch'),
      codeWidget(codeToggleButtonsWidget, 'ToggleButtons'),
      codeWidget(codeCheckboxWidget, 'Checkbox'),
      codeWidget(codeRadioWidget, 'Radio'),
      codeWidget(codeDatePickerWidget, 'DatePicker'),
      codeWidget(codeTimePickerWidget, 'TimePicker'),
      codeWidget(codeDropdownButtonWidget, 'DropdownButton'),
    ]),

    'Image': MapEntry(const ImageWidgetTutorial(),
        [codeWidget(codeImageWidgetTutorial, 'Image')]),

    // Add more mappings as needed
  };

  static Widget getWidget(String widgetName) {
    final MapEntry<Widget, List<Widget>>? entry = widgetMapping[widgetName];
    return entry?.key ?? Container();
  }

  static List<Widget> getWidgetCode(String widgetName) {
    final MapEntry<Widget, List<Widget>>? entry = widgetMapping[widgetName];
    return entry?.value ?? [];
  }
}

Widget codeWidget(String codeString, String widgetName) {
  return Column(
    children: [
      Text(widgetName),
      const SizedBox(
        height: 10,
      ),
      HighlightView(
        codeString,
        language: 'dart',
        theme: githubTheme,
        padding: const EdgeInsets.all(6),
      ),
    ],
  );
}
